"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.offer_api import OfferApi  # noqa: E501


class TestOfferApi(unittest.TestCase):
    """OfferApi unit test stubs"""

    def setUp(self):
        self.api = OfferApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_create_offer(self):
        """Test case for bulk_create_offer

        """
        pass

    def test_bulk_publish_offer(self):
        """Test case for bulk_publish_offer

        """
        pass

    def test_create_offer(self):
        """Test case for create_offer

        """
        pass

    def test_delete_offer(self):
        """Test case for delete_offer

        """
        pass

    def test_get_listing_fees(self):
        """Test case for get_listing_fees

        """
        pass

    def test_get_offer(self):
        """Test case for get_offer

        """
        pass

    def test_get_offers(self):
        """Test case for get_offers

        """
        pass

    def test_publish_offer(self):
        """Test case for publish_offer

        """
        pass

    def test_publish_offer_by_inventory_item_group(self):
        """Test case for publish_offer_by_inventory_item_group

        """
        pass

    def test_update_offer(self):
        """Test case for update_offer

        """
        pass

    def test_withdraw_offer(self):
        """Test case for withdraw_offer

        """
        pass

    def test_withdraw_offer_by_inventory_item_group(self):
        """Test case for withdraw_offer_by_inventory_item_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
