"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.listing_api import ListingApi  # noqa: E501


class TestListingApi(unittest.TestCase):
    """ListingApi unit test stubs"""

    def setUp(self):
        self.api = ListingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_migrate_listing(self):
        """Test case for bulk_migrate_listing

        """
        pass


if __name__ == '__main__':
    unittest.main()
