"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.inventory_item_group_api import InventoryItemGroupApi  # noqa: E501


class TestInventoryItemGroupApi(unittest.TestCase):
    """InventoryItemGroupApi unit test stubs"""

    def setUp(self):
        self.api = InventoryItemGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_or_replace_inventory_item_group(self):
        """Test case for create_or_replace_inventory_item_group

        """
        pass

    def test_delete_inventory_item_group(self):
        """Test case for delete_inventory_item_group

        """
        pass

    def test_get_inventory_item_group(self):
        """Test case for get_inventory_item_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
