"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.name_value_list import NameValueList
from openapi_client.model.product_family_properties import ProductFamilyProperties
from openapi_client.model.product_identifier import ProductIdentifier
globals()['NameValueList'] = NameValueList
globals()['ProductFamilyProperties'] = ProductFamilyProperties
globals()['ProductIdentifier'] = ProductIdentifier
from openapi_client.model.compatible_product import CompatibleProduct


class TestCompatibleProduct(unittest.TestCase):
    """CompatibleProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompatibleProduct(self):
        """Test CompatibleProduct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompatibleProduct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
