"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.inventory_item_api import InventoryItemApi  # noqa: E501


class TestInventoryItemApi(unittest.TestCase):
    """InventoryItemApi unit test stubs"""

    def setUp(self):
        self.api = InventoryItemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bulk_create_or_replace_inventory_item(self):
        """Test case for bulk_create_or_replace_inventory_item

        """
        pass

    def test_bulk_get_inventory_item(self):
        """Test case for bulk_get_inventory_item

        """
        pass

    def test_bulk_update_price_quantity(self):
        """Test case for bulk_update_price_quantity

        """
        pass

    def test_create_or_replace_inventory_item(self):
        """Test case for create_or_replace_inventory_item

        """
        pass

    def test_delete_inventory_item(self):
        """Test case for delete_inventory_item

        """
        pass

    def test_get_inventory_item(self):
        """Test case for get_inventory_item

        """
        pass

    def test_get_inventory_items(self):
        """Test case for get_inventory_items

        """
        pass


if __name__ == '__main__':
    unittest.main()
