"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.location_api import LocationApi  # noqa: E501


class TestLocationApi(unittest.TestCase):
    """LocationApi unit test stubs"""

    def setUp(self):
        self.api = LocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_inventory_location(self):
        """Test case for create_inventory_location

        """
        pass

    def test_delete_inventory_location(self):
        """Test case for delete_inventory_location

        """
        pass

    def test_disable_inventory_location(self):
        """Test case for disable_inventory_location

        """
        pass

    def test_enable_inventory_location(self):
        """Test case for enable_inventory_location

        """
        pass

    def test_get_inventory_location(self):
        """Test case for get_inventory_location

        """
        pass

    def test_get_inventory_locations(self):
        """Test case for get_inventory_locations

        """
        pass

    def test_update_inventory_location(self):
        """Test case for update_inventory_location

        """
        pass


if __name__ == '__main__':
    unittest.main()
