"""
    Inventory API

    The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.  # noqa: E501

    The version of the OpenAPI document: 1.13.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.location_details import LocationDetails
from openapi_client.model.operating_hours import OperatingHours
from openapi_client.model.special_hours import SpecialHours
globals()['LocationDetails'] = LocationDetails
globals()['OperatingHours'] = OperatingHours
globals()['SpecialHours'] = SpecialHours
from openapi_client.model.inventory_location_full import InventoryLocationFull


class TestInventoryLocationFull(unittest.TestCase):
    """InventoryLocationFull unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInventoryLocationFull(self):
        """Test InventoryLocationFull"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InventoryLocationFull()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
